name = "AstrophysicalCalculations"
uuid = "fd9cccc2-a1d0-4073-bc0f-e265a877cbf5"
authors = ["Joey Carpinelli <joey@loopy.codes>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
DynamicQuantities = "0.7, 0.8"
Reexport = "1.2"
StaticArrays = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
